# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget EngineAICore::src_app EngineAICore::src_common_base EngineAICore::src_common_containers EngineAICore::src_common_monitor EngineAICore::src_common_parameter EngineAICore::src_common_tool EngineAICore::src_core_estimator_base_state_estimator EngineAICore::src_core_estimator_motion_state_estimator EngineAICore::src_core_estimator_parallel_ankle EngineAICore::src_core_estimator_parallel_palms EngineAICore::src_core_math EngineAICore::src_core_model EngineAICore::src_data EngineAICore::src_hardware_common EngineAICore::src_hardware_imu EngineAICore::src_runner_basic EngineAICore::src_runner_imu EngineAICore::src_runner_joint_motor_transform_runner EngineAICore::src_runner_motor EngineAICore::src_runner_param_server EngineAICore::src_runner_sim_publish EngineAICore::src_runner_sim_subscribe EngineAICore::src_runner_whole_body_estimate EngineAICore::src_task)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target EngineAICore::src_app
add_library(EngineAICore::src_app SHARED IMPORTED)

set_target_properties(EngineAICore::src_app PROPERTIES
  INTERFACE_LINK_LIBRARIES "EngineAICore::src_common_tool;EngineAICore::src_task;EngineAICore::src_runner_basic;EngineAICore::src_runner_imu;EngineAICore::src_runner_joint_motor_transform_runner;EngineAICore::src_runner_motor;EngineAICore::src_runner_param_server;EngineAICore::src_runner_sim_publish;EngineAICore::src_runner_sim_subscribe;EngineAICore::src_runner_whole_body_estimate"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_common_base
add_library(EngineAICore::src_common_base SHARED IMPORTED)

set_target_properties(EngineAICore::src_common_base PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_common_tool"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_common_containers
add_library(EngineAICore::src_common_containers INTERFACE IMPORTED)

set_target_properties(EngineAICore::src_common_containers PROPERTIES
  INTERFACE_LINK_LIBRARIES "${ENGINEAI_ROBOTICS_THIRD_PARTY_ROOT}/lib/libsodium.so"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_common_monitor
add_library(EngineAICore::src_common_monitor SHARED IMPORTED)

set_target_properties(EngineAICore::src_common_monitor PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_data;EngineAICore::src_common_containers"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_common_parameter
add_library(EngineAICore::src_common_parameter SHARED IMPORTED)

set_target_properties(EngineAICore::src_common_parameter PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_common_tool;EngineAICore::src_core_math"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_common_tool
add_library(EngineAICore::src_common_tool SHARED IMPORTED)

set_target_properties(EngineAICore::src_common_tool PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;${ENGINEAI_ROBOTICS_THIRD_PARTY_ROOT}/lib/libsodium.so"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_core_estimator_base_state_estimator
add_library(EngineAICore::src_core_estimator_base_state_estimator SHARED IMPORTED)

set_target_properties(EngineAICore::src_core_estimator_base_state_estimator PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_data;EngineAICore::src_core_math;EngineAICore::src_common_monitor"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_core_estimator_motion_state_estimator
add_library(EngineAICore::src_core_estimator_motion_state_estimator SHARED IMPORTED)

set_target_properties(EngineAICore::src_core_estimator_motion_state_estimator PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_data;EngineAICore::src_core_math"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_core_estimator_parallel_ankle
add_library(EngineAICore::src_core_estimator_parallel_ankle SHARED IMPORTED)

set_target_properties(EngineAICore::src_core_estimator_parallel_ankle PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_data;EngineAICore::src_core_math;EngineAICore::src_common_parameter"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_core_estimator_parallel_palms
add_library(EngineAICore::src_core_estimator_parallel_palms SHARED IMPORTED)

set_target_properties(EngineAICore::src_core_estimator_parallel_palms PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_data;EngineAICore::src_core_math;EngineAICore::src_common_parameter;EngineAICore::src_core_model"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_core_math
add_library(EngineAICore::src_core_math SHARED IMPORTED)

set_target_properties(EngineAICore::src_core_math PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${ENGINEAI_ROBOTICS_THIRD_PARTY_ROOT}/include"
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_common_tool;${ENGINEAI_ROBOTICS_THIRD_PARTY_ROOT}/lib/libMNN.so;${ENGINEAI_ROBOTICS_THIRD_PARTY_ROOT}/lib/libqpOASES.so"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_core_model
add_library(EngineAICore::src_core_model SHARED IMPORTED)

set_target_properties(EngineAICore::src_core_model PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;pinocchio::pinocchio;EngineAICore::src_core_math;EngineAICore::src_data"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_data
add_library(EngineAICore::src_data SHARED IMPORTED)

set_target_properties(EngineAICore::src_data PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_common_parameter"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_hardware_common
add_library(EngineAICore::src_hardware_common SHARED IMPORTED)

set_target_properties(EngineAICore::src_hardware_common PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_hardware_imu
add_library(EngineAICore::src_hardware_imu SHARED IMPORTED)

set_target_properties(EngineAICore::src_hardware_imu PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;Boost::thread;EngineAICore::src_hardware_common"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_runner_basic
add_library(EngineAICore::src_runner_basic SHARED IMPORTED)

set_target_properties(EngineAICore::src_runner_basic PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_data;EngineAICore::src_common_monitor;EngineAICore::src_common_tool;EngineAICore::src_core_math"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_runner_imu
add_library(EngineAICore::src_runner_imu SHARED IMPORTED)

set_target_properties(EngineAICore::src_runner_imu PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_runner_basic;EngineAICore::src_hardware_imu"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_runner_joint_motor_transform_runner
add_library(EngineAICore::src_runner_joint_motor_transform_runner SHARED IMPORTED)

set_target_properties(EngineAICore::src_runner_joint_motor_transform_runner PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_runner_basic;EngineAICore::src_core_estimator_parallel_ankle;EngineAICore::src_core_estimator_parallel_palms"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_runner_motor
add_library(EngineAICore::src_runner_motor SHARED IMPORTED)

set_target_properties(EngineAICore::src_runner_motor PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_runner_basic;EngineAICore::src_data;${ENGINEAI_ROBOTICS_HARDWARE_ROOT}/lib/libmotor.so"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_runner_param_server
add_library(EngineAICore::src_runner_param_server SHARED IMPORTED)

set_target_properties(EngineAICore::src_runner_param_server PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;EngineAICore::src_runner_basic;lcm"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_runner_sim_publish
add_library(EngineAICore::src_runner_sim_publish SHARED IMPORTED)

set_target_properties(EngineAICore::src_runner_sim_publish PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_runner_basic;lcm"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_runner_sim_subscribe
add_library(EngineAICore::src_runner_sim_subscribe SHARED IMPORTED)

set_target_properties(EngineAICore::src_runner_sim_subscribe PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_runner_basic;lcm"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_runner_whole_body_estimate
add_library(EngineAICore::src_runner_whole_body_estimate SHARED IMPORTED)

set_target_properties(EngineAICore::src_runner_whole_body_estimate PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_runner_basic;EngineAICore::src_core_model;EngineAICore::src_core_estimator_base_state_estimator;EngineAICore::src_core_estimator_motion_state_estimator"
  INTERFACE_SOURCES ""
)

# Create imported target EngineAICore::src_task
add_library(EngineAICore::src_task SHARED IMPORTED)

set_target_properties(EngineAICore::src_task PROPERTIES
  INTERFACE_LINK_LIBRARIES "yaml-cpp::yaml-cpp;glog::glog;fmt::fmt;Eigen3::Eigen;EngineAICore::src_common_base;EngineAICore::src_data;EngineAICore::src_runner_basic"
  INTERFACE_SOURCES ""
)

if(CMAKE_VERSION VERSION_LESS 3.1.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.1.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/EngineAICoreTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
